"""Initial migration

Revision ID: 0ef08e47c300
Revises: 
Create Date: 2025-08-02 22:22:15.621850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef08e47c300'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fitment_-_primenyaemost', sa.Column('name', sa.String(), nullable=True))
    op.add_column('media', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'name')
    op.drop_column('fitment_-_primenyaemost', 'name')
    # ### end Alembic commands ###
