"""initial

Revision ID: 1db647f7f212
Revises: 6b6f4a084282
Create Date: 2025-08-02 16:27:37.264513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db647f7f212'
down_revision: Union[str, None] = '6b6f4a084282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'ozon_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('categories', 'wb_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('categories_yandex_category_id_fkey'), 'categories', type_='foreignkey')
    op.drop_column('categories', 'yandex_category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('yandex_category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('categories_yandex_category_id_fkey'), 'categories', 'marketplace_categories', ['yandex_category_id'], ['id'])
    op.alter_column('categories', 'wb_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('categories', 'ozon_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
