"""empty message

Revision ID: b0f0a46978d4
Revises: c2f251608bb2
Create Date: 2025-08-06 23:25:05.495763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f0a46978d4'
down_revision: Union[str, None] = 'c2f251608bb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('yandex_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'marketplace_categories', ['yandex_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'yandex_category_id')
    # ### end Alembic commands ###
