"""Создание всех таблиц из файла заказчика

Revision ID: c2f251608bb2
Revises: 
Create Date: 2025-08-05 14:02:22.384823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2f251608bb2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('characteristics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('box_size', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('quantity_text', sa.String(), nullable=False),
    sa.Column('quantity_number', sa.Integer(), nullable=False),
    sa.Column('tn_ved', sa.String(), nullable=False),
    sa.Column('guarantee', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fitment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(), nullable=False),
    sa.Column('make_translit', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('model_translit', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('year_1', sa.Integer(), nullable=False),
    sa.Column('year_2', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(), nullable=False),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('engine_capacity', sa.Integer(), nullable=False),
    sa.Column('engine_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marketplace', sa.Enum('OZON', 'WB', 'YANDEX', name='marketplace_enum'), nullable=False),
    sa.Column('external_id', sa.BIGINT(), nullable=False),
    sa.Column('parent_external_id', sa.BIGINT(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type_id', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marketplace', 'external_id', name='uq_marketplace_external_id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_1', sa.String(), nullable=False),
    sa.Column('image_2', sa.String(), nullable=False),
    sa.Column('image_3', sa.String(), nullable=False),
    sa.Column('image_4', sa.String(), nullable=False),
    sa.Column('image_5', sa.String(), nullable=False),
    sa.Column('image_6', sa.String(), nullable=False),
    sa.Column('image_7', sa.String(), nullable=False),
    sa.Column('image_8', sa.String(), nullable=False),
    sa.Column('image_9', sa.String(), nullable=False),
    sa.Column('image_10', sa.String(), nullable=False),
    sa.Column('rich', sa.String(), nullable=False),
    sa.Column('video', sa.String(), nullable=False),
    sa.Column('video_cover', sa.String(), nullable=False),
    sa.Column('pdf_instruction', sa.String(), nullable=False),
    sa.Column('certificate', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oem_brand', sa.String(), nullable=False),
    sa.Column('oem_sku', sa.String(), nullable=False),
    sa.Column('cross_brand', sa.String(), nullable=False),
    sa.Column('cross_sku', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ozon_fitment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ozon_sku', sa.String(), nullable=False),
    sa.Column('make', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('modification', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Integer(), nullable=False),
    sa.Column('price_ozon', sa.Integer(), nullable=False),
    sa.Column('profitability', sa.Integer(), nullable=False),
    sa.Column('profit', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('price_before_discount', sa.Integer(), nullable=False),
    sa.Column('vat', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('marketplace', sa.Enum('OZON', 'WB', 'YANDEX', name='marketplaceenum'), nullable=False),
    sa.Column('alias_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'marketplace', 'alias_name', name='uq_brand_alias')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ozon_category_id', sa.Integer(), nullable=True),
    sa.Column('wb_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ozon_category_id'], ['marketplace_categories.id'], ),
    sa.ForeignKeyConstraint(['wb_category_id'], ['marketplace_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('used_sku', sa.String(), nullable=True),
    sa.Column('sku_1', sa.String(), nullable=True),
    sa.Column('sku_2', sa.String(), nullable=True),
    sa.Column('common_sku', sa.String(), nullable=True),
    sa.Column('part_number', sa.Integer(), nullable=True),
    sa.Column('ozon_sku', sa.String(), nullable=True),
    sa.Column('ozon_id', sa.Integer(), nullable=True),
    sa.Column('wb_id', sa.Integer(), nullable=True),
    sa.Column('yandex_id', sa.Integer(), nullable=True),
    sa.Column('id_1c', sa.Integer(), nullable=True),
    sa.Column('id_mp', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('size_id', sa.Integer(), nullable=True),
    sa.Column('price_id', sa.Integer(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('fitment_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['fitment_id'], ['fitment.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['characteristics.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('categories')
    op.drop_table('brand_aliases')
    op.drop_table('prices')
    op.drop_table('ozon_fitment')
    op.drop_table('oem')
    op.drop_table('media')
    op.drop_table('marketplace_categories')
    op.drop_table('fitment')
    op.drop_table('characteristics')
    op.drop_table('brands')
    # ### end Alembic commands ###
