# Generated by Django 5.2.4 on 2025-08-02 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('OZON', 'Ozon'), ('WB', 'Wb'), ('YANDEX', 'Yandex')], max_length=20)),
                ('external_id', models.BigIntegerField()),
                ('parent_external_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('full_path', models.CharField(blank=True, max_length=255, null=True)),
                ('type_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'marketplace_categories',
                'unique_together': {('marketplace', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ozon_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ozon_categories', to='categories.marketplacecategory')),
                ('wb_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wb_categories', to='categories.marketplacecategory')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
