# Generated by Django 5.2.4 on 2025-08-02 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'brendy',
            },
        ),
        migrations.CreateModel(
            name='Fitment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'fitment_-_primenyaemost',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'kategorii_mp',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'media',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('used_sku', models.CharField(blank=True, max_length=255, null=True)),
                ('sku_1', models.CharField(blank=True, max_length=255, null=True)),
                ('sku_2', models.CharField(blank=True, max_length=255, null=True)),
                ('common_sku', models.CharField(blank=True, max_length=255, null=True)),
                ('ozon_sku', models.CharField(blank=True, max_length=255, null=True)),
                ('part_number', models.CharField(blank=True, max_length=255, null=True)),
                ('id_1c', models.CharField(blank=True, max_length=255, null=True)),
                ('id_mp', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('wb_sku', models.CharField(blank=True, max_length=255, null=True)),
                ('ozon_update', models.DateTimeField(blank=True, null=True)),
                ('wb_update', models.DateTimeField(blank=True, null=True)),
                ('multiplicity', models.IntegerField(blank=True, null=True)),
                ('activity', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(db_column='brand', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand', to_field='name')),
                ('fitment', models.ForeignKey(db_column='fitment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.fitment')),
                ('media', models.ForeignKey(db_column='media_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.media')),
                ('type', models.ForeignKey(db_column='type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.marketplacecategory')),
            ],
            options={
                'db_table': 'nomenklatura',
            },
        ),
    ]
