# Generated by Django 5.2.4 on 2025-08-02 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(db_column='type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.marketplacecategory'),
        ),
        migrations.DeleteModel(
            name='MarketplaceCategory',
        ),
    ]
