# Generated by Django 5.2.4 on 2025-08-02 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_ozon_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wb_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
